version: '3.9'

services:
  app:
    image: alpine:latest
    command: ["sh", "-c", "cat /run/secrets/my_secret && sleep 3600"]
    secrets:
      - my_secret

secrets:
  my_secret:
    file: ./secrets/my_secret
