FROM debian:bullseye

RUN apt-get update -y && apt-get upgrade -y 

RUN apt-get install make git gcc nano ftp -y

COPY ./uftpd.cfg ./uftpd.cfg

RUN git clone https://github.com/kingk85/uFTP.git

RUN cd uFTP

RUN make

RUN cp build/uFTP /sbin/uFTP

RUN cd ..
RUN cp uftpd.cfg uFTP/etc/uftpd.cfg
RUN cd uFTP

RUN chown root:root /sbin/uFTP
RUN chown root:root /etc/uftpd.cfg
RUN chmod -rwx /etc/uftpd.cfg


# Expose the FTP port (21)
EXPOSE 21
# EXPOSE 40000:50000

# CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
# CMD ["vsftpd", "--no-detach", "/etc/vsftpd.conf"]
# vsftpd --no-detach /etc/vsftpd.conf

# CMD ["/sbin/uFTP", "-D"]
CMD ["uFTP"]
# ENTRYPOINT ["uFTP"]
