
# images names must be changed!!!!!!
# version: '3.8'

##################################################
# --------------------- VOLUMES ---------------- #
##################################################

volumes:
  vol_nginx_wordpress:
  vol_mariadb:
  vol_kuma:

##################################################
# --------------------- NETWORKS --------------- #
##################################################

networks:
  net_inception:
    name: net_inception
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

##################################################
# --------------------- SECRETS----------------- #
##################################################
secrets:
  wp_admin_pw:
    file: ./secrets/wp_admin_pw.txt
  db_user_pw:
    file: ./secrets/db_user_pw.txt
  db_root_pw:
    file: ./secrets/db_root_pw.txt

services:
##################################################
# --------------------- NGINX ------------------ #
##################################################

  nginx:
    container_name: nginx
    image: my_nginx_img
    build: ./requirements/nginx/.
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    networks:
        net_inception:
          ipv4_address: 192.168.1.99
    volumes:
      - vol_nginx_wordpress:/var/www/html

##################################################
# --------------------- MARIADB ---------------- #
##################################################

  mariadb:
    container_name: mariadb
    image: my_maridb_img
    build: ./requirements/mariadb/.
    restart: always
    env_file:
      - .env
    environment:
      - DB_USER_PW=/run/secrets/db_user_pw
      - DB_ROOT_PW=/run/secrets/db_root_pw
    secrets:
      - db_user_pw
      - db_root_pw
    networks:
        net_inception:
          ipv4_address: 192.168.1.100
    volumes:
      - vol_mariadb:/var/lib/mysql

##################################################
# --------------------- WORDPRESS -------------- #
##################################################

  wordpress:
    container_name: wordpress
    image: my_wordpress_img
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    environment:
      - WP_ADMIN_PW=/run/secrets/wp_admin_pw
      - DB_USER_PW=/run/secrets/db_user_pw
    secrets:
      - source: wp_admin_pw
        target: /run/secrets/wp_admin_pw
      # - wp_admin_pw
      - db_user_pw
    networks:
        net_inception:
          ipv4_address: 192.168.1.101
    volumes:
      - vol_nginx_wordpress:/var/www/html
  
##################################################
# --------------------- BONUS ------------------ #
##################################################
# --------------------- REDIS ------------------ #
##################################################

  redis:
    container_name: redis
    image: my_redis_img
    build: ./requirements/bonus/redis/.
    restart: always
    depends_on:
      - wordpress
    networks:
        net_inception:
          ipv4_address: 192.168.1.102
    volumes:
      - vol_nginx_wordpress:/var/www/html

##################################################
# --------------------- FTP -------------------- #
##################################################

  # ftp:
  #   container_name: ftp
  #   image: my_ftp_img
  #   build: ./requirements/bonus/ftp/.
  #   restart: always
  #   depends_on:
  #     - wordpress
    # networks:
    #     net_inception:
    #       ipv4_address: 192.168.1.103
  #   volumes:
  #     - vol_nginx_wordpress:/var/www/html
  #   ports:
  #     - 21:21

##################################################
# --------------------- ADMINER ---------------- #
##################################################

  adminer:
    container_name: adminer
    image: my_adminer_img
    build: ./requirements/bonus/adminer/.
    restart: always
    depends_on:
      - mariadb
    networks:
        net_inception:
          ipv4_address: 192.168.1.104
    volumes:
      - vol_mariadb:/var/lib/mysql
    ports:
      - 8080:80

##################################################
# --------------------- WEBSITE ---------------- #
##################################################

  website:
    container_name: website
    image: my_website_img
    build: ./requirements/bonus/website/.
    restart: always
    networks:
        net_inception:
          ipv4_address: 192.168.1.105
    ports:
      - 85:80


##################################################
# --------------------- KUMA ------------------- #
##################################################

  kuma:
    container_name: kuma
    image: my_kuma_img
    build: ./requirements/bonus/kuma/.
    restart: always
    depends_on:
      - website
    networks:
        - net_inception
    volumes:
      - vol_kuma:/app/data
    ports:
      - 3001:3001
