
services:

  nginx:
    container_name: nginx
    image: my_nginx_img
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
        - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html


  # mariadb:
  #   container_name: mariadb
  #   image: mariadb
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=your_root_password
  #     - MYSQL_DATABASE=your_database
  #     - MYSQL_USER=your_user
  #     - MYSQL_PASSWORD=your_password
  #   healthcheck:
  #     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3
  #   ports:
  #     - 3306:3306
  #   networks:
  #       - net_inception
  #   volumes:
  #     - vol_mariadb:/var/lib/mysql


  # wordpress:
  #   container_name: wp-php
  #   image: wordpress:latest
  # #   build: ./requirements/wordpress
  #   depends_on:
  #     - mariadb
  #   environment:
  #     WORDPRESS_DB_HOST: db
  #     WORDPRESS_DB_USER: user
  #     WORDPRESS_DB_PASSWORD: pass
  #     WORDPRESS_DB_NAME: database
  #   ports:
  #     - 9000:9000
  #   networks:
  #       - net_inception
  #   volumes:
  #     - vol_nginx_wordpress:/var/www/html
    

volumes:
  vol_nginx_wordpress:
  vol_mariadb:


networks:
  net_inception:
    name: net_inception
    driver: bridge

