
# images names must be changed!!!!!!


volumes:
  vol_nginx_wordpress:
  vol_mariadb:
  vol_kuma:


networks:
  net_inception:
    name: net_inception
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24

services:

  nginx:
    container_name: nginx
    image: my_nginx_img
    build: ./requirements/nginx/.
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    networks:
        net_inception:
          ipv4_address: 192.168.1.99
    volumes:
      - vol_nginx_wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    image: my_maridb_img
    build: ./requirements/mariadb/.
    restart: always
    # script is missing!!!!
    # healthcheck:
    #   test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    #   start_period: 10s
    #   interval: 10s
    #   timeout: 15s
    #   retries: 3
    env_file:
      - .env
    networks:
        - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql

  wordpress:
    container_name: wordpress
    image: my_wordpress_img
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    networks:
        - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html
  
  redis:
    container_name: redis
    image: my_redis_img
    build: ./requirements/bonus/redis/.
    restart: always
    depends_on:
      - wordpress
    networks:
        - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html
    # command: ["redis-server", "/etc/redis/redis.conf"]  # Explicit command
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   interval: 10s
    #   retries: 5
    #   start_period: 30s
    #   timeout: 10s

  # ftp:
  #   container_name: ftp
  #   image: my_ftp_img
  #   build: ./requirements/bonus/ftp/.
  #   restart: always
  #   depends_on:
  #     - wordpress
  #   networks:
  #       - net_inception
  #   volumes:
  #     - vol_nginx_wordpress:/var/www/html
  #   ports:
  #     - 21:21

  adminer:
    container_name: adminer
    image: my_adminer_img
    build: ./requirements/bonus/adminer/.
    restart: always
    depends_on:
      - mariadb
    networks:
        - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql
    ports:
      - 8080:80

  website:
    container_name: website
    image: my_website_img
    build: ./requirements/bonus/website/.
    restart: always
    networks:
        net_inception:
          ipv4_address: 192.168.1.100
    ports:
      - 85:80

  kuma:
    container_name: kuma
    image: my_kuma_img
    build: ./requirements/bonus/kuma/.
    restart: always
    depends_on:
      - website
    networks:
        - net_inception
    volumes:
      - vol_kuma:/app/data
      - vol_kuma:/app/data
    ports:
      - 3001:3001
