
# images names must be changed!!!!!!


volumes:
  vol_nginx_wordpress:
  vol_mariadb:


networks:
  net_inception:
    name: net_inception
    # driver: bridge


services:

  nginx:
    container_name: nginx
    image: my_nginx_img
    build: ./requirements/nginx/.
    restart: always
    # depends_on:
    #   - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    networks:
        - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html

  mariadb:
    container_name: mariadb
    image: my_maridb_img
    build: ./requirements/mariadb/.
    restart: always
    # script is missing!!!!
    # healthcheck:
    #   test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
    #   start_period: 10s
    #   interval: 10s
    #   timeout: 15s
    #   retries: 3
    env_file:
      - .env
    networks:
        - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql
  #   ports:
  #     - 3306:3306

  wordpress:
    container_name: wordpress
    image: my_wordpress_img
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
      - nginx
    env_file:
      - .env
    networks:
        - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html
  #   ports:
  #     - 9000:9000