
services:

  nginx:
    container_name: nginx
    image: my_nginx_img
    build: ./requirements/nginx
    ports:
      - 443:443
    networks:
        - net_inception
    volumes:
      - vol_nginx_wp:/var/www/html

  mariadb:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    ports:
      - 3306:3306
    networks:
        - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql

  # wordpress:
  #   container_name: wp-php
  #   #image: wordpress:latest
  #   build: ./requirements/wordpress







volumes:
  vol_nginx_wp:
    name: vol_nginx_wp
  vol_mariadb:
    name: vol_mariadb

networks:
  net_inception:
    name: net_inception



  # mariadb:
  #   container_name: mariadb
  #   build: ./requirements/mariadb
  # #  image: mariadb:latest
  #   restart: always
  #   env_file:
  #     - ../secrets/.env
  #   volumes:
  #     - vol_mariadb:/var/lib/mysql
  #   networks:
  #     - net_mariadb
  #   healthcheck:
  #     test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
  #     start_period: 10s
  #     interval: 10s
  #     timeout: 5s
  #     retries: 3


# volumes:
#   vol_mariadb:
#     name: vol_mariadb
#     driver_opts:
#       o: bind
#       type: none
#       # NEEDS TO BE CHANGED!!!
#       device: $HOME/Desktop/42_Inception/data/mariadb




  # wordpress:
  #   container_name: wordpress42
  #   build: ./requirements/wordpress/
  #   #image: wordpress:latest
  #   restart: always
  #   ports:
  #     - 8081:80
  #   # depends_on:
  #   #   mariadb:
  #   #     condition: service_healthy
  #   env_file:
  #     - ../secrets/.env
  #   volumes:
  #     - volume_wordpress:/var/www/html
