
##################################################
# --------------------- VOLUMES ---------------- #
##################################################

volumes:
  vol_nginx_wordpress:
  vol_mariadb:
  vol_kuma:

##################################################
# --------------------- NETWORKS --------------- #
##################################################

networks:
  net_inception:
    name: net_inception

##################################################
# --------------------- SECRETS----------------- #
##################################################

secrets:
  wp_admin_pw:
    file: ./secrets/wp_admin_pw
  db_user_pw:
    file: ./secrets/db_user_pw
  db_root_pw:
    file: ./secrets/db_root_pw
  ftp_pw:
    file: ./secrets/ftp_pw

services:
##################################################
# --------------------- NGINX ------------------ #
##################################################

  nginx:
    container_name: nginx
    image: nginx
    build: ./requirements/nginx/.
    restart: always
    depends_on:
      - wordpress
    env_file:
      - .env
    ports:
      - 443:443
    networks:
      - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html

##################################################
# --------------------- MARIADB ---------------- #
##################################################

  mariadb:
    container_name: mariadb
    image: maridb
    build: ./requirements/mariadb/.
    restart: always
    env_file:
      - .env
    secrets:
      - db_user_pw
      - db_root_pw
    networks:
      - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql

##################################################
# --------------------- WORDPRESS -------------- #
##################################################

  wordpress:
    container_name: wordpress
    image: wordpress
    build: ./requirements/wordpress/.
    restart: always
    depends_on:
      - mariadb
    env_file:
      - .env
    secrets:
      - wp_admin_pw
      - db_user_pw
    networks:
      - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html
  
##################################################
# --------------------- BONUS ------------------ #
##################################################
# --------------------- REDIS ------------------ #
##################################################

  redis:
    container_name: redis
    image: redis
    build: ./requirements/bonus/redis/.
    restart: always
    depends_on:
      - wordpress
    networks:
      - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html

##################################################
# --------------------- FTP -------------------- #
##################################################

  ftp:
    container_name: ftp
    image: ftp
    build: ./requirements/bonus/ftp/.
    restart: always
    depends_on:
      - wordpress
    networks:
      - net_inception
    volumes:
      - vol_nginx_wordpress:/var/www/html
    ports:
      - 21:21
      # - 20:20
    env_file:
      - .env
    secrets:
      - ftp_pw

##################################################
# --------------------- ADMINER ---------------- #
##################################################

  adminer:
    container_name: adminer
    image: adminer
    build: ./requirements/bonus/adminer/.
    restart: always
    depends_on:
      - mariadb
    networks:
      - net_inception
    volumes:
      - vol_mariadb:/var/lib/mysql
    ports:
      - 8080:80

##################################################
# --------------------- WEBSITE ---------------- #
##################################################

  website:
    container_name: website
    image: website
    build: ./requirements/bonus/website/.
    restart: always
    networks:
      - net_inception
    ports:
      - 85:80


##################################################
# --------------------- KUMA ------------------- #
##################################################

  kuma:
    container_name: kuma
    image: kuma
    build: ./requirements/bonus/kuma/.
    restart: always
    networks:
        - net_inception
    volumes:
      - vol_kuma:/app/data
    ports:
      - 3001:3001
